Pre kr 8.x
laravelkr/docs pull request #402
Opened 2022-02-13 18:31 UTC by N0FreeLunch

controllers, errors, hasing 8.x 문서에 맞게 번역 했습니다. controllers의 경우 원문에 삭제된 부분이 많아서 원문에 맞게 지웠습니다. 혹시라도 모르니 한번 검토 하시는 게 좋을 것 같습니다.

2022-02-14 18:10 UTC, N0FreeLunch commented
지워도 무방할 것 같은 역자주를 모두 삭제했으며, 문서로 이해할 수 있도록 좀 더 의역을 하였습니다. 
표현상 어색한 부분을 좀 더 의역하는 방향으로 수정했고, 번역기에 의한 표기 미스 부분 찾아서 모두 수정했습니다. 
hashing 부분의 work factor의 경우 설명을 하지 않으면 이해가 어려울 수 있다고 판단했기 때문에 역자주를 하나 남겼습니다.

2022-02-17 07:52 UTC, Kyungseo-Park commented
아래 파라미터 링크를 보시면 `>` 표기가 잘못 되어 있습니다.  
https://github.com/laravelkr/docs/blob/5fd487ac2d741f963790b193a5ccfad61b28b64e/kr/controllers.md?plain=1#L136  
```
>> {tip} [stub publishing](/docs/{{version}}/artisan#stub-customization)를 사용하여 controller stub을 사용자가 정의할 수 있습니다.
```

2022-02-17 08:33 UTC, Kyungseo-Park requested changes

2022-02-17 08:33 UTC, Kyungseo-Park commented on kr/controllers.md
여기 다음줄에 \>\> 이라 표기 되있습니다.

2022-02-17 08:33 UTC, Kyungseo-Park commented on kr/errors.md
> +> {Tip} 내부적으로 라라벨은 편의를 위해 몇몇 타입의 에러를 무시합니다. 404 HTTP "not found" 에러 또는 CSRF 토큰 인증을 통과하지 못한 경우에 발생하는 419 HTTP responses generated 등의 에러 입니다.
{Tip} 은 소문자 표기입니다..!

2022-02-17 08:36 UTC, aihoshistar commented
번역 정말 깔끔하십니다 :+1:

2022-02-18 12:40 UTC, merged

2022-02-18 12:40 UTC, kkame commented
수고하셨습니다!

2022-02-18 12:42 UTC, kkame commented
@all-contributors please add @N0FreeLunch for doc