Pre kr 8.x
laravelkr/docs pull request #410
Opened 2022-02-15 17:23 UTC by 1ocate

validation.md 번역

2022-02-17 06:52 UTC, Kyungseo-Park requested changes

2022-02-17 06:52 UTC, Kyungseo-Park commented on kr/verification.md
> +[Laravel application starter kits](/docs/{{version}}/starter-kits)을 사용할 때 라라벨은 이메일 검증 과정에서 [이벤트](/docs/{{version}}/events)를 전달합니다. 여러분의 애플리케이션에 대한 이메일 검증을 수동으로 처리하는 경우, 이메일 검증 완료 이벤트를 수동으로 전달할 수 있습니다
여러분 애플리케이션의 'EventServiceProvider'에서 이벤트에 리스너를 연결할 수 있습니다. 보시면  
'EventServiceProvider' => \`EventServiceProvider\` 으로 변경해주셔야합니다.   
따옴표가 아니 백쿼트(`)!

2022-02-17 06:58 UTC, Kyungseo-Park requested changes

2022-02-17 06:58 UTC, Kyungseo-Park commented on kr/verification.md
> +다음으로 request-요청에서 `fulfill` 메소드를 직접 호출하여 진행할 수 있습니다. 이 메소드는 `MarkEmailAsVerified` 메소드를 호출하고 검증된 사용자를 `Illuminate\Auth\Events\Verified` 이벤트에 전달 합니다. 이 `MarkEmailAsVerified` 메소드는 기본 클래스 `Illuminate\Fou
\`MarkEmailAsVerified\`와 \`MarkEmailAsVerified\` 첫 단어는 소문자 입니다

2022-02-17 07:38 UTC, 1ocate commented on kr/verification.md
> +다음으로 request-요청에서 `fulfill` 메소드를 직접 호출하여 진행할 수 있습니다. 이 메소드는 `MarkEmailAsVerified` 메소드를 호출하고 검증된 사용자를 `Illuminate\Auth\Events\Verified` 이벤트에 전달 합니다. 이 `MarkEmailAsVerified` 메소드는 기본 클래스 `Illuminate\Fou
수정완료
감사합니다.

2022-02-17 07:38 UTC, 1ocate commented
감사합니다 수정 완료 했습니다.

2022-02-17 12:20 UTC, kkame reviewed
수고하셨습니다!

한가지 수정요청이 있어서 코멘트 남겼는데 이 부분 확인부탁드립니다

2022-02-17 12:20 UTC, kkame commented on kr/verification.md
> +다음으로 사용자가 이메일로 받은 검증 링크를 클릭 할 때 생성 된 요청을 처리 할 라우터를 정의 해야 합니다. 이 라우터의 name은 `Verification.Verify`로 정의하고 `auth` 및 `signed` 미들웨어를 할당해야 합니다.
여기서 `verification.verify` 부분이 번역하면서 대문자가 들어간 것 같습니다 수정 부탁드립니다

2022-02-17 13:47 UTC, 1ocate commented on kr/verification.md
> +다음으로 사용자가 이메일로 받은 검증 링크를 클릭 할 때 생성 된 요청을 처리 할 라우터를 정의 해야 합니다. 이 라우터의 name은 `Verification.Verify`로 정의하고 `auth` 및 `signed` 미들웨어를 할당해야 합니다.
왜이렇게 되었을까요 ㅠ 수정했습니다.

2022-02-17 13:47 UTC, 1ocate commented
추가 수정사항 완료 하였습니다.

2022-02-18 12:45 UTC, merged

2022-02-18 12:47 UTC, kkame commented
수고하셨습니다!

@all-contributors please add @1ocate for doc

2022-02-18 13:10 UTC, kkame commented
제목과 본문에서 언급되는 파일명이 달라서 제가 임의로 수정하였습니다. 양해부탁드립니다