notifications.md 번역본 지적사항 1차 수정
laravelkr/docs pull request #424
Opened 2022-02-19 08:10 UTC by evans-kim

notifications.md 번역본 지적사항 1차 수정

2022-02-20 05:45 UTC, Kyungseo-Park requested changes
번역 하시느라 고생 많으셨습니다. 

kkame 님이 바쁘셔서 kkame 님이 리뷰하시기 전 제가 대신해서 감히 제가 리뷰를 해드렸습니다. 
한번 확인하시고 수정 부탁드립니다!

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +  - [필요시 대상을 지정한 Notifications](#on-demand-notifications)
목차 부분에서 Tab 이 4칸이 아닌 2칸으로 되있습니다.
원문에는 Tab이 4칸으로 되있으니 확인 부탁드립니다!

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +그러나 대기열 작업자가 처리한 후 대기열에 있는 알림을 보낼지 여부를 최종 결정하려면 알림 클래스에 'shouldSend' 메소드를 정의할 수 있습니다. 이 메소드가 'false'를 반환하면 알림이 전송되지 않습니다.
'shouldSend' 와 'false'를 는 따옴표(') 가 아닌 \`shouldSend\` 와 \`false\`  처럼 백쿼터(\`) 입니다

백쿼터를 사용하면  `shouldSend` 와 `false` 처럼 강조가 됩니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +때로는 애플리케이션의 "User"모델로 저장되지 않은 사람에게 알림을 보내야 할 수도 있습니다. 'Notification' 파사드의 'route' 메소드를 사용하여 알림을 보내기 전에 임시 알림 라우팅 정보를 지정할 수 있습니다.
이 부분도 'Notification', 'route' 부분을 백쿼터로 변경해주셔야합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +필요에 따라 임시적인 알림을 'mail' 경로로 보낼 때 수신자의 이름을 제공하려면 이메일 주소를 키로 포함하고 이름을 배열의 첫 번째 요소 값으로 포함하는 배열을 제공해야 합니다.
'mail' to \`mail\` 입니다. 백쿼터로 변경 부탁드립니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +알림이 이메일로 전송되는 것을 지원하는 경우 알림 클래스에 `toMail` 메소드를 정의해야 합니다. 이 메소드는 `notifiable` 구현체를 수신하고 `Illuminate\Notifications\Messages\MailMessage` 인스턴스를 반환해야 합니다.
$가 누락되었습니다.
`notifiable` 는 `$notifiable` 으로 표시 해주셔아합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +이 예시에서는 인사말, 한 줄의 텍스트, 클릭 유도 및 다른 텍스트 줄을 등록합니다. `MailMessage` 객체에서 제공하는 이러한 메소드를 사용하면 작은 트랜잭션 이메일을 간단하고 빠르게 포맷할 수 있습니다. 그러면 메일 채널은 메시지를 일반 텍스트에서 아름답고 반응이 빠른 HTML 이메일 템플릿으로 변환합니다. 다음은 `mail` 채널에서 생성된
한글로 번역된 문장의 마지막에 있는 : 는 제거 해주셔야 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +#### 기타 메일 알림 형식 옵션
기타 메일 알림 포매팅 옵션으로 바꾸는건 어떨지 @kkame  님의 의견을 여쭙고 싶습니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +기본적으로 이메일 제목은 "Title Case" 형식의 알림 클래스 이름입니다. 따라서 알림 클래스의 이름이 `InvoicePaid`인 경우 이메일 제목은 'Invoice Paid'가 됩니다. 메시지에 다른 제목을 지정하려면 메시지를 작성할 때 `subject` 메소드를 호출할 수 있습니다.
'Invoice Paid'가 됩니다. 의 문장에서도 백쿼터로 표시 해주셔야 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +필요한 경우 알림의 `toMail` 메소드에서 전체 [메일가능한 객체](docs/{{version}}/mail)을 반환할 수 있습니다. `MailMessage` 대신 `Mailable`을 반환할 때 메일 가능 객체의 `to` 메소드를 사용하여 메시지 수신자를 지정해야 합니다.:
한글로 번역된 문장에서는 : 를 빼주셔야 합니다

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +
`notifiable` 를 `$notifiable` 으로 수정해 주셔야 합니다

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +다른 모든 메일 알림과 마찬가지로 Markdown 템플릿을 사용하는 알림은 알림 클래스에 'toMail' 메소드를 정의해야 합니다. 그러나 `line` 및 `action` 메소드를 사용하여 알림을 설정하는 대신 `markdown` 메소드를 사용하여 사용해야 하는 Markdown 템플릿의 이름을 지정합니다. 템플릿에서 사용할 수 있도록 하려는 데이터 배열이
'toMail' to \`toMail\` 으로 백쿼터를 추가해 주셔야 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +알림이 데이터베이스에 저장되면 알림 인스턴스에서 액세스할 수 있는 편리한 방법이 필요합니다. 라라벨의 기본 `App\Models\User` 모델에 포함된 `Illuminate\Notifications\Notifiable` 트레이스에는 알림을 가져오기 위해 다른 Eloquent 관계처럼 이 방법에 액세스할 수 있는 모델가 있습니다. 기본적으로 알림은 컬렉션
\[Eloquent relationship\]\(/docs/{{version}}/eloquent-relationships\) 에 대한 문장이 누락된거 같습니다

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +알림을 브로드캐스팅하기 전에 라라벨의 [이벤트 브로드캐스팅](docs/{{version}}/broadcasting) 서비스를 설정하고 숙지해야 합니다. 이벤트 브로드캐스팅은 JavaScript 기반 프론트엔드에서 서버 측 Laravel 이벤트에 반응하는 방법을 제공합니다.
한글 문서에서 Laravel 은 라라벨로 표기하고 있다 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +`broadcast` 채널은 Laravel의 [이벤트 브로드캐스팅](docs/{{version}}/broadcasting) 서비스를 사용하여 알림을 브로드캐스트하므로 JavaScript 기반 프론트엔드가 실시간으로 알림을 받을 수 있습니다. 알림이 브로드캐스팅을 지원하는 경우 알림 클래스에서 'toBroadcast' 메소드를 정의할 수 있습니다. 이 메소
'toBroadcast' 와 'BroadcastMessage' 를 백쿼터로 수정 해주셔야 합니다

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +Laravel에서 SMS 알림 보내기는 [Vonage](https://www.vonage.com)(이전 Nexmo로 알려짐)에서 제공합니다. Vonage를 통해 알림을 보내기 전에 `laravelnexmo-notification-channel` 및 `nexmolaravel` Composer 패키지를 설치해야 합니다.
한글 문서에서 Laravel은 라라벨로 표기하고 있습니다. 

laravelnexmo-notification-channel 에 / 가 누락 되었습니다. 
laravel/nexmo-notification-channel 으로 변경해주셔야 합니다 

`nexmolaravel` 에 / 가 누락되어 `nexmo/laravel` 으로 수정해주셔아 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +알림이 SMS로 전송되는 것을 지원하는 경우 알림 클래스에 `toNexmo` 메소드를 정의해야 합니다. 이 메소드는 `notifiable` 모델를 수신하고 `Illuminate\Notifications\Messages\NexmoMessage` 인스턴스를 반환해야 합니다.
`notifiable` 에 $ 가 누락되었습니다. `$notifiable` 으로 표기 해주셔야 합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +팀을 위한 [Slack 앱](https//:api.slack.com/apps?new_app=1)도 생성해야 합니다. 앱을 생성한 후 작업 영역에 대해 "Incoming Webhook"을 설정해야 합니다. 그러면 Slack에서 [Slack 알림 라우팅](#routing-slack-notifications) 시 사용할 수 있는 웹훅 URL을 제공합니다.
Slack 앱의 링크가 잘못 되었습니다. 
https//:api.slack.com/apps?new_app=1 의 https//:   를 보시면 : 가 // 뒤에 있습니다. // 앞으로 이동 해주셔야합니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +알림이 Slack 메시지로 전송되는 것을 지원하는 경우 알림 클래스에 'toSlack' 메소드를 정의해야 합니다. 이 메소드는 `notifiable` 모델을 수신하고 `Illuminate\Notifications\Messages\SlackMessage` 인스턴스를 반환해야 합니다. Slack 메시지에는 추가 텍스트 또는 필드 배열의 형식을 지정하는 "첨부
'toSlack' to \`toSlack\` 으로 변경 해주셔야 합니다. 
\`notifiable\` 에 $ 가 누락 되있습니다.

2022-02-20 05:45 UTC, Kyungseo-Park commented on kr/notifications.md
> +`send` 메소드 내에서 알림에 대한 메소드를 호출하여 채널에서 이해하는 메시지 개체를 검색한 다음 원하는 대로 `notifiable` 인스턴스에 알림을 보낼 수 있습니다.
`notifiable` 에 $ 가 누락 되었습니다.

2022-02-20 08:10 UTC, evans-kim commented on kr/notifications.md
> +  - [필요시 대상을 지정한 Notifications](#on-demand-notifications)
네, 커밋하면서 스타일이 자동으로 변경하는 옵션이 영향을 준 것 같네요. 주의해서 올리겠습니다.

2022-02-20 08:12 UTC, evans-kim commented on kr/notifications.md
> +#### 기타 메일 알림 형식 옵션
기존의 네이밍을 최대한 따라가는 게 맞을 거 같습니다. @Kyungseo-Park 님의 의견대로 수정하겠습니다.

2022-02-20 08:23 UTC, evans-kim commented
@Kyungseo-Park  님 꼼꼼히 읽어 주셔서 감사합니다. 기존 번역본에 추가하는 게 아니라 처음부터 전 페이지를 작업하느라 빼먹은 디테일이 많았네요. 지적하신 부분은 다 수정하였습니다. 감사합니다!

2022-02-21 15:22 UTC, kkame reviewed
수고하셨습니다!

일부 수정이 필요한 부분이 있어서 코멘트를 남겼는데 확인 부탁드립니다!

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +특히 채널이 알림을 전달하기 위해 외부 API를 호출해야 하는 경우 알림을 보내는 데 시간이 걸릴 수 있습니다. 애플리케이션의 응답 시간을 단축하려면 `ShouldQueue` 인터페이스와 `Queueable` 특성을 클래스에 추가하여 알림을 대기열에 추가하세요. 인터페이스와 특성은 `make:notification` 명령을 사용하여 생성된 모든 알림에 대
trait는 특성으로 번역할 경우 일반적으로 한번에 trait 을 떠올리기 어려운 것 같습니다.

그래서 가급적이면 trait 이라고 영어 그대로 남기거나 `특성-trait` 이라고 번역해주시면 더 좋을 것 같습니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +특정 채널에 대한 지연을 설정하기 위해 배열을 `delay` 메소드에 전달할 수 있습니다:
끝에 마침표를 `:`를 `.`로 수정 부탁드립니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +> {tip} 이러한 문제를 해결하는 방법에 대해 자세히 알아보려면 관련 문서를 검토하세요. [대기 중인 작업 및 데이터베이스 트랜잭션](/docs/{{version}}/queues#jobs-and-database-transactions).
여기서는 링크의 위치를 수정해서 


> {tip} 이러한 문제를 해결하는 방법에 대해 자세히 알아보려면 [대기 중인 작업 및 데이터베이스 트랜잭션](/docs/{{version}}/queues#jobs-and-database-transactions) 관련 문서를 검토하세요.

로 번역하면 어떨까요?

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +그러나 대기열 작업자가 처리한 후 대기열에 있는 알림을 보낼지 여부를 최종 결정하려면 알림 클래스에 `shouldSend` 메소드를 정의할 수 있습니다. 이 메소드가 'false`를 반환하면 알림이 전송되지 않습니다.
여기서 `false`의 마크다운 표기가 잘못되어있습니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +이메일 알림에 첨부 파일을 추가하려면 메시지를 작성하는 동안 `attach` 메소드을 사용하세요. `attach` 메소드는 파일의 절대 경로를 첫 번째 인수로 받아들입니다.:
마지막에 `:` 삭제 부탁드립니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +메시지에 파일을 첨부할 때 `attach` 메소드의 두 번째 인수로 `array`를 전달하여 표시 이름, MIME 유형을 지정할 수도 있습니다.:
여기도 `:` 삭제 부탁드립니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +알림이 전송되면 알림 시스템에서 `Illuminate\Notifications\Events\NotificationSending` [event](docs/{{version}}/events)을 전달합니다. 여기에는 "notifiable" 모델과 알림 인스턴스 자체가 포함됩니다. 애플리케이션의 `EventServiceProvider`에서 이 이벤트에 대한 리스
[event](docs/{{version}}/events) 여기서 링크가 잘못되었습니다

2022-02-21 15:22 UTC, kkame commented on kr/notifications.md
> +알림이 전송되면 알림 시스템에서 `Illuminate\Notifications\Events\NotificationSent` [event](docs/{{version}}/events)를 전달합니다. 여기에는 "notifiable" 모델와 알림 인스턴스 자체가 포함됩니다. `EventServiceProvider`에서 이 이벤트에 대한 리스너를 등록할 수 있습
[event](docs/{{version}}/events) 링크가 잘못되었습니다

2022-02-22 08:07 UTC, evans-kim commented on kr/notifications.md
> +특히 채널이 알림을 전달하기 위해 외부 API를 호출해야 하는 경우 알림을 보내는 데 시간이 걸릴 수 있습니다. 애플리케이션의 응답 시간을 단축하려면 `ShouldQueue` 인터페이스와 `Queueable` 특성을 클래스에 추가하여 알림을 대기열에 추가하세요. 인터페이스와 특성은 `make:notification` 명령을 사용하여 생성된 모든 알림에 대
네 원문 그대로 두겠습니다.

2022-02-22 08:12 UTC, evans-kim commented
@kkame 님의 지적사항을 모두 수정하였습니다. 감사합니다.

2022-02-26 08:40 UTC, merged

2022-02-26 08:41 UTC, kkame commented
양이 많았는데 정말 수고하셨습니다 !

@all-contributors please add @evans-kim for doc