Cashier-Paddle.md 추가번역 및 수정
laravelkr/docs pull request #427
Opened 2022-02-20 05:10 UTC by Mo-zang

Cashier-Paddle 수정 및 번역 완료 하였습니다~

2022-02-20 06:09 UTC, Kyungseo-Park requested changes
어우야 고생 많으셨습니다.

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +  - [기본 모델 재정의](#overriding-default-models)
목차에서 탭이 2칸으로 되있습니다. 원문에서는 4칸으로 되있으니 확인 부탁드립니다!

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +[Laravel Cashier Paddle](https://github.comlaravelcashier-paddle)은 [Paddle](https://paddle.com) 구독 결제 서비스에 대한 쉽고 편리한 인터페이스를 제공합니다. 패들은 당신이 두려워하는 거의 모든 상용 구독 청구 코드를 처리합니다. 기본 구독 관리 외에도 캐셔는 쿠폰, 구독 교환,
링크가 잘못 되있습니다. 
https://github.comlaravelcashier-paddle 에서 /laravel/cashier-paddle 으로 변경 해주셔야 합니다.

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +캐셔로 작업하는 동안 Paddle의 [사용자 가이드](https://developer.paddle.comguides) 및 [API 문서](https://developer.paddle.comapi-referenceintro)도 함께 보는것이 좋습니다
링크가 잘못 되있습니다.
https://developer.paddle.comguides 와 https://developer.paddle.comapi-referenceintro 도 https://developer.paddle.com/guides 와 https://developer.paddle.com/api-reference/intro 으로 수정 해주셔ㅑ 합니다.

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +로컬 및 스테이징 개발 중에 [Paddle Sandbox](https://developer.paddle.comgetting-startedsandbox)계정을 등록해야 합니다. 이 계정은 실제 지불 없이 애플리케이션을 테스트하고 개발할 수 있는 샌드박스 환경을 제공합니다. 패들의 [테스트 카드 번호](https://developer.paddle.comget
https://developer.paddle.comgetting-startedsandbox 여기도 링크가 잘못 첨부되어 있습니다. (/ 가 누락)

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +### Database Migrations
데이터베이스 마이그레이션 으로 번역하는게 어떨까요?

2022-02-20 06:09 UTC, aihoshistar commented on kr/cashier-paddle.md
> +[패들의 샌드박스 환경](#paddle-sandbox) 사용 시 'PADDLE_SANDBOX' 환경 변수를 'true'로 설정해야 합니다. 애플리케이션을 프로덕션에 배포하고 Paddle의 라이브 공급업체 환경을 사용하는 경우 `PADDLE_SANDBOX` 변수를 `false`로 설정해야 합니다.
'PADDLE_SANDBOX' 에서 따옴표가 사용 되었습니다. 백쿼터 (\`) 를 사용 해주셔야합니다.
백쿼터를 사용하시면 \`PADDLE_SANDBOX\` 가 `PADDLE_SANDBOX` 으로 표시 됩니다. 

'true' 도 \`true\` 으로 변경 해주셔야 합니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +다음으로 HTML의 'a' 요소에 유료 링크 URL을 첨부하기만 하면 됩니다.
'a' 를 \`a\` 으로 변경 해주셔야합니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +Laravel의 내장 Blade 컴포넌트를 사용하지 않고 인라인 체크아웃을 수동으로 렌더링할 수도 있습니다. 시작하려면 [유료 링크 URL](#pay-links)을 생성하십시오.
한글 번역본에서 Laravel 은 라라벨로 표기하기로 했습니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
'create'  에 백쿼터를 사용해 주셔야합니다. 

docs{{version}}bladecomponents 에 / 와 # 가 누락 되었습니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +추가 고객 또는 구독 세부 정보를 지정하려면 키 값 쌍의 배열로 'create' 메서드에 전달하면 됩니다. Paddle에서 지원하는 추가 필드에 대해 자세히 알아보려면 [지불 링크 생성](https://developer.paddle.com/api-reference/product-api/pay-links/createpaylink)에 대한 Paddle의 문서
'create' 를 백쿼터로 변경 해주셔야 합니다. 

key / value 는 키 / 값 으로 번역하므로 원문을 참고해서 `키 값 쌍의` 문장을 `키 / 값` 으로 변경하면 어떨까요?

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +사용자가 아직 평가판 기간 내에 있는지 확인하려면 'onTrial' 방법을 사용할 수 있습니다. 이 방법은 사용자에게 아직 평가판 기간에 대한 경고를 표시해야 하는지 여부를 결정하는 데 유용할 수 있습니다.
'onTrial' 를 백쿼터로 변경 해주셔야 합니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +구독 기한이 지난 경우 사용자에게 [결제 정보 업데이트](#updating-payment-information)를 안내해야 합니다. [패들 구독 설정](https:vendors.paddle.comsubscription-settings)에서 연체 구독을 처리하는 방법을 구성할 수 있습니다.
https:vendors.paddle.comsubscription-settins 에 링크가 잘못 되었습니다 . 확인 부탁드립낟.

// 와 / 가 누락 되었습니다.

2022-02-20 06:09 UTC, Kyungseo-Park commented on kr/cashier-paddle.md
> +### Past & Upcoming Payments
원문에는 과거 및 향후 지급으로 되있습니다. 
과거 및 향후 지급 으로 수정하는건 어떨지 의견 여쭙고자 합니다..!

2022-02-20 11:21 UTC, Mo-zang commented on kr/cashier-paddle.md
> +### Past & Upcoming Payments
뭔가 어감이 이상한거 같아서 그냥 영어로 두었는데, 이전 문서에는 그렇게 되어있으니 그대로 돌려두는 쪽으로 진행하도록 하겠습니다 ㅎㅎ 감사합니다

2022-02-20 11:46 UTC, Mo-zang commented
리뷰 달아주신 부분들 수정 완료하였습니다. 바쁘실탠데 확인 감사합니다 ㅎㅎ

2022-02-21 16:07 UTC, kkame reviewed
수고하셨습니다! 몇가지 코멘트가 있는데 확인부탁드립니다

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +# Laravel Cashier (Paddle)
제목이 사라졌습니다

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +PADDLE_SANDBOX=true
여기 왠지 앞에 탭이 있었어야 할 것 같은 느낌인데 원문과 한번 더 체크해봐주세요

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +#### Manually Rendering Pay Links
여기 번역이 누락되었습니다

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +
여기 엔터가 한번 더 들어갔습니다

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +때때로 구독은 "수량"의 영향을 받습니다. 예를 들어 프로젝트 관리 응용 프로그램은 프로젝트당 월 10달러를 청구할 수 있습니다. 구독 수량을 쉽게 늘리거나 줄이려면 `incrementQuantity` 및 `decrementQuantity` 메서드를 사용하세요.
여기서 `응용 프로그램`은 `애플리케이션`으로 통일하고 있는 단어인데  수정부탁드립니다

2022-02-21 16:07 UTC, kkame commented on kr/cashier-paddle.md
> +청구는 `cashier.currency` 구성 옵션에 지정된 통화로 발생합니다. 기본적으로 USD로 설정되어 있습니다. 애플리케이션의 `.env` 파일에서 `CASHIER_CURRENCY` 환경 변수를 정의하여 기본 통화를 재정의할 수 있습니다.
`구성`은 가급적이면 `설정`으로 번역하려고 하는 중인데 문맥상 이상하지 않다면 설정으로 통일 부탁드립니다

2022-02-26 04:18 UTC, Mo-zang commented
리뷰 남겨주신 부분들 수정하다 '유료' 라는 문구가 어색해보여 문맥상 '결제' 로 변경하는것이 좋을거같아 같이 수정하였습니다.!

2022-02-26 08:07 UTC, merged

2022-02-26 08:07 UTC, kkame commented
수고하셨습니다~