mix.md 8.x 버전에 맞게 번역
laravelkr/docs pull request #428
Opened 2022-02-20 19:16 UTC by N0FreeLunch

원문에 삭제된 단락 제거 및 추가된 단락 추가 번역 및 어색한 부분 자연스럽게 고침

2022-02-20 23:39 UTC, Kyungseo-Park requested changes
어우야 번역 하시느라 고생 많으셨습니다!!

kkame 님이 바쁘셔서 kkame 님이 리뷰하시기 전 제가 대신하여 감히.. 리뷰를 해드렸습니다.
한번 확인하시고 수정 부탁드립니다!

TMI로 대부분 번역 이슈는 4가지가 있는 것 같습니다만.. 아래 이슈는 한개도 없었습니다. 
멋지십니다.. 

1. 한글 문장 끝에 : 가 붙는 것
2. 따옴표(')와 백쿼터(`) 를 잘못 표기하는 것
3. $변수 에 $ 가 누락 되는 것
4. URL 이 잘못 입력된 경우

2022-02-20 23:39 UTC, Kyungseo-Park commented on kr/mix.md
> +  - [소스 맵](#css-source-maps)
탭이 줄간격 2칸으로 되있습니다.

2022-02-20 23:39 UTC, Kyungseo-Park commented on kr/mix.md
한글 번역본에서 Laravel 은 라라벨로 통일하기로 했다 합니다..!

2022-02-21 15:36 UTC, merged

2022-02-21 15:37 UTC, kkame commented
제가 따로 코멘트 드릴게 없네요! 수고하셨습니다!